=== LordKrabo/org.geppetto.core/src/main/resources/schema/simulation/simulationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openworm.org/simulationSchema"
	xmlns:tns="http://www.openworm.org/simulationSchema"
	elementFormDefault="qualified" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="2.0">


	<element name="geppettoModel">
		<complexType>
			<sequence>
				<element name="entity" type="tns:Entity" maxOccurs="unbounded"
					minOccurs="1">
					<annotation>
						<appinfo>
							<jxb:property name="entities" />
						</appinfo>
					</annotation>
				</element>
			</sequence>
		</complexType>
	</element>

	<complexType name="Model">
		<sequence>
			<element name="modelInterpreterId" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="modelURL" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="instancePath" type="string" maxOccurs="1" minOccurs="0"></element>
			<element name="parentAspect" type="tns:Aspect" maxOccurs="1" minOccurs="0"></element>
			<element name="recordingURL" type="string" maxOccurs="unbounded" minOccurs="0"></element>
			<element name="referenceURL" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="Point3D">
		<sequence>
			<element name="x" type="float" maxOccurs="1" minOccurs="1"></element>
			<element name="y" type="float" maxOccurs="1" minOccurs="1"></element>
			<element name="z" type="float" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>

	<simpleType name="ConnectionType">
		<restriction base="string">
			<enumeration value="FROM" />
			<enumeration value="TO" />
			<enumeration value="UNDIRECTED" />
		</restriction>
	</simpleType>
	
	<complexType name="VisualObjectReference">
		<sequence>
			<element name="aspectInstancePath" type="string"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="visualObjectID" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="id" type="string" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>
	
	<complexType name="CustomProperty">
		<sequence>
			<element name="name" type="string"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="value" type="float" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="id" type="string" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>
	
	<complexType name="Aspect">
		<sequence>
			<element name="id" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="instancePath" type="string" maxOccurs="1" minOccurs="0"></element>
			<element name="model" type="tns:Model" maxOccurs="1"
				minOccurs="0"></element>
			<element name="parentEntity" type="tns:Entity" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="Entity">
		<sequence>
			<element name="id" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="instancePath" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="aspect" type="tns:Aspect"
				maxOccurs="unbounded" minOccurs="1">
				<annotation>
					<appinfo>
						<jxb:property name="aspects" />
					</appinfo>
				</annotation>
			</element>
			<element name="parentEntity" type="tns:Entity" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="entity" type="tns:Entity"
				maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<appinfo>
						<jxb:property name="entities" />
					</appinfo>
				</annotation>
			</element>
			<element name="position" type="tns:Point3D" minOccurs="0"
				maxOccurs="1">
			</element>
            <element name="connection" type="tns:Connection" 
            	maxOccurs="unbounded" minOccurs="0">
            	<annotation>
					<appinfo>
						<jxb:property name="connections" />
					</appinfo>
				</annotation>
            </element>
        </sequence>
	</complexType>
	
	<complexType name="Connection">
		<sequence>
			<element name="id" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="entityInstancePath" type="string" maxOccurs="1" minOccurs="0"></element>
			<element name="type" type="tns:ConnectionType" maxOccurs="1"
				minOccurs="1"></element>
			<element name="visualReference" type="tns:VisualObjectReference"
				maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<appinfo>
						<jxb:property name="visualObjectReferences" />
					</appinfo>
				</annotation>
			</element>
			<element name="customProperty" type="tns:CustomProperty"
				maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<appinfo>
						<jxb:property name="customProperties" />
					</appinfo>
				</annotation>
			</element>
		</sequence>
	</complexType>

	
</schema>

=== LordKrabo/org.geppetto.core/src/main/resources/workInProgress/SPHLiquidSmall/GEPPETTO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:geppettoModel xmlns:tns="http://www.openworm.org/simulationSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openworm.org/simulationSchema ../../main/resources/schema/simulation/simulationSchema.xsd">
	<tns:entity>
		<tns:id>sample</tns:id>
		<tns:aspect>
			<tns:id>fluid</tns:id>
			<tns:model>
    				<tns:modelInterpreterId>sphModelInterpreter</tns:modelInterpreterId>
    				<tns:modelURL>/projects/SPHLiquidSmall/sphModel_liquid_780.xml</tns:modelURL>
			</tns:model>
		</tns:aspect>		
	</tns:entity>	
</tns:geppettoModel>

=== LordKrabo/org.geppetto.core/src/main/resources/projects/EyeWireGanglionCell/GEPPETTO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:geppettoModel xmlns:tns="http://www.openworm.org/simulationSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openworm.org/simulationSchema ../../main/resources/schema/simulation/simulationSchema.xsd">
	<tns:entity>
		<tns:id>ganglioncelll</tns:id>
		<tns:aspect>
			<tns:id>morphology</tns:id>
			<tns:model>
    				<tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
    				<tns:modelURL>/projects/EyeWireGanglionCell/eyewiresample.obj</tns:modelURL>
			</tns:model>
		</tns:aspect>		
	</tns:entity>
</tns:geppettoModel>
